version: '3.8'

services:
  backend:
    # Указываем путь до Dockerfile чтобы собрать контейнер
    build: ./backend
    # Определяем порты на которых будет запущен бекенд и по которому будет доступно подключение
    ports:
      - 5000:5000
    # Монтируем во внутрь app директорию с исходным кодом python + poetry
    volumes:
      - ./backend/src:/app
      - ./backend/pyproject.toml:/app/pyproject.toml
    # Запускаем приложение через uvicorn
    command: "poetry run python main.py"
