version: '3.8'

services:
  backend:
    # Указываем путь до Dockerfile чтобы собрать контейнер
    build: ./backend
    restart: unless-stopped
    # Определяем порты на которых будет запущен бекенд и по которому будет доступно подключение
    ports:
      - 5000:5000
    env_file: .docker.env
    # Монтируем во внутрь app директорию с исходным кодом python + poetry
    volumes:
      - ./backend/src:/app/src
      - ./backend/migrations:/app/migrations
      - ./backend/alembic.ini:/app/alembic.ini
    # Запускаем приложение через uvicorn
    command: "poetry run python src/main.py"
    # command: "sleep infinity"

  frontend:
    build: ./frontend
    restart: unless-stopped
    env_file: .docker.env
    ports:
      - 8080:8080
    # command: sleep infinity
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules

  # pgbouncer:

  database:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=fastapi_user
      - POSTGRES_PASSWORD=fastapi_pass
      - POSTGRES_DB=fastapi_dev
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db:
  node_modules:
