version: '3.8'

services:

  backend:
    container_name: web_notepad_backend
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    restart: unless-stopped
    ports:
      - 5000:5000
    env_file: .docker.env
    command: poetry run uvicorn app.main:app --host 0.0.0.0 --port 5000 --reload
    # command: sleep infinity

