version: '3.8'

services:
  backend:
    # Указываем путь до Dockerfile чтобы собрать контейнер
    build: ./backend
    restart: unless-stopped
    # Определяем порты на которых будет запущен бекенд и по которому будет доступно подключение
    ports:
      - 5000:5000
    environment:
      # Путь до БД
      # PGPASSWORD=fastapi_pass psql -h localhost -p 5432 -U fastapi_user -d fastapi_dev
      # postgresql://{USER}:{PASSWORD}@{HOST}:{PORT}/{DB_NAME}
      - DATABASE_URL=postgresql://fastapi_user:fastapi_pass@database:5432/fastapi_dev
    # Монтируем во внутрь app директорию с исходным кодом python + poetry
    volumes:
      - ./backend/src:/app/src
      - ./backend/migrations:/app/migrations
      - ./backend/alembic.ini:/app/alembic.ini
    # Запускаем приложение через uvicorn
    command: "poetry run python src/main.py"

  # frontend:
  #   build: ./frontend
  #   restart: unless-stopped
  #   ports:
  #     - 8080:8080
  #   volumes:
  #     - ./frontend:/app
  #     # - /app/node_modules

  # pgbouncer:

  database:
    image: postgres:13
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=fastapi_user
      - POSTGRES_PASSWORD=fastapi_pass
      - POSTGRES_DB=fastapi_dev
    volumes:
      - db:/var/lib/postgresql/data/

volumes:
  db: