"""author not null

Revision ID: 020222149eb3
Revises: 43ddf6574e0e
Create Date: 2022-08-14 15:18:20.835663

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '020222149eb3'
down_revision = '43ddf6574e0e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('notes', 'author_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###
