"""add password2

Revision ID: 2685b5e3b077
Revises: 22f84acf4b4c
Create Date: 2022-07-11 07:07:53.983274

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2685b5e3b077'
down_revision = '22f84acf4b4c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password2', sa.String(length=256), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password2')
    # ### end Alembic commands ###
