"""

Revision ID: 43ddf6574e0e
Revises: 26beb7b9d22f
Create Date: 2022-08-14 14:29:13.407511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '43ddf6574e0e'
down_revision = '26beb7b9d22f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
