"""rename password

Revision ID: 855d6d5b7667
Revises: b77fd056b1a0
Create Date: 2022-07-11 07:12:10.251164

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '855d6d5b7667'
down_revision = 'b77fd056b1a0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.String(length=256), nullable=True))
    op.drop_column('users', 'password2')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password2', sa.VARCHAR(length=256), autoincrement=False, nullable=True))
    op.drop_column('users', 'password')
    # ### end Alembic commands ###
