"""remove password

Revision ID: b77fd056b1a0
Revises: 2685b5e3b077
Create Date: 2022-07-11 07:11:29.003564

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b77fd056b1a0'
down_revision = '2685b5e3b077'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'password')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('password', sa.VARCHAR(length=128), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
